### ISSUE TITLE
Add issue and PR templates similar to those used in CFS

### ISSUE THREAD

**Issue by jphickey** [nasa/bplib#119]
BP and BPLib development needs to follow NPR 7150, and part of the documentation requirements are fulfilled by tracking who is requesting changes and who is implementing them, along with why it is needed.

CFS has templates for issues and PRs that aim to capture this information geared toward fulfilling those requirements.  BP and BPLib should be able to use the same templates.

**Comment by thnkslprpt** [comment]
On a related note @jphickey - would you like me to scrub bplib for some of the comment/empty-line issues I scrubbed the cFS components/apps for this week?
(e.g. empty line first or last line of a function, redundant comments like '`/* end of function */`' etc.)

**Comment by dzbaker** [comment]
@thnkslprpt That would be great, thanks! There might not be any of those issues in BPLib, although it would be good to make sure. Also, would you be able to fill out a CLA for BPLib (as BPLib has a different one than cFS)?

**Comment by thnkslprpt** [comment]
> @thnkslprpt That would be great, thanks! There might not be any of those issues in BPLib, although it would be good to make sure. Also, would you be able to fill out a CLA for BPLib (as BPLib has a different one than cFS)?

Will do. No worries.
I emailed the CLA just now.
