### ISSUE TITLE
Typos in bplib cause coverage test not run

### ISSUE THREAD

**Issue by glan6388** [nasa/bplib#190]
**Describe the bug**
Typos in CMakeLists.txt in function add_test() caused all bplib coverage tests not run.

**To Reproduce**
To duplicate, run "make ENABLE_UNIT_TESTS=true prep", then run "make", then run "make test", all bplib unit tests will not run because of name inconsistent.

**Comment by jphickey** [comment]
I suspect these two items are unrelated and will have separate fixes to address them.  Can we split this into two separate issues?

**Comment by glan6388** [comment]
Hi Joe,

Yes, they are, but I thought the fixes are in the same files. I will try to split them.
Thanks,

George
________________________________

**Comment by glan6388** [comment]
Done and assigned them to myself.
________________________________
