### ISSUE TITLE
Reconsider requirement for separate RAM and FILE storage backends

### ISSUE THREAD

**Issue by jphickey** [nasa/bplib#32]
These two backends seem to do the same thing but just use a different storage.  On many systems it may be possible to get the same effect with only a "file" back end.

Basically, one could create a file backend but locate it on a ramdisk, or in something like the /dev/shm directory on linux.  This has the added advantage of giving some external visibility to how large the storage is.

**Comment by jpswinski** [comment]
Good idea.  The code does not limit the number of storage services that can be provided, and in the future, developing a file storage service (or modifying the current one) to support a ramdisk would be a good idea.  But I still want to keep the RAM storage service for targets that don't have a file system.
