### ISSUE TITLE
disabling UNITTESTS yields empty translation units

### ISSUE THREAD

**Issue by jphickey** [nasa/bplib#34]
Source files like `unittest/ut_rh_hash.c` are always compiled, but if UNITTESTS is disabled then this file is effectively empty.  ISO C forbids empty translation units (although gcc allows it unless you turn on pedantic mode).

These files should be removed from the makefile if UNITTESTS is disabled, not `#ifdef`'d out.

**Comment by jpswinski** [comment]
Fixed - the unit test files are only compiled when UNITTESTS is set, and the UNITTESTS #ifdef is used only for whether or not the unit test functions are called.

ff7d72cca1a5957d5bd527e571d553e8b3848088
