### ISSUE TITLE
It is customary to externally set `CC` to specify a cross compiler

### ISSUE THREAD

**Issue by jphickey** [nasa/bplib#36]
https://github.com/nasa/bplib/blob/17d228c27ed93e1f3bf8b93091afa0319e3a6e28/Makefile#L148-L149

Particularly when cross comiling, it is customary to externally set the `CC` environment variable to the path of the cross compiler.  Furthermore GNU make will automatically set `CC` to a reasonable default so it is generally not necessary to set these explicitly in the Makefile.

**Comment by jphickey** [comment]
Also note that typically the `O` variable indicates the output (build dir), not optimization level.

**Comment by jpswinski** [comment]
The commit above also removed the O variable for optimization level and relies instead of just adding it to the COPT variable.
