### ISSUE TITLE
Suggest using a return value of 0 as BP_SUCCESS

### ISSUE THREAD

**Issue by jphickey** [nasa/bplib#39]
It is customary, particularly in the UNIX/POSIX world that functions return an integer value of 0 to indicate success.  This is true of basically every system library call.

Consider at least swapping the BP_SUCCESS and BP_TIMEOUT values here:
https://github.com/nasa/bplib/blob/17d228c27ed93e1f3bf8b93091afa0319e3a6e28/inc/bplib.h#L51-L52

**Comment by jpswinski** [comment]
0cd2008bea89ba8fcc8eaaf9873cfb1adf603694

Refactored the return codes as recommended.  Made some return codes flags instead and made the flag use more consistent.

**Comment by jpswinski** [comment]
5a1d958ceeb8de2a490862465465b2bf22f0d411
